# Trip Duration Variability

## Definition

The 80th/20th Percentile ratio of durations between specified points on a vehicle’s trip. Reported for the start of the TSP corridor to the end of the TSP corridor and between each Timepoint along the TSP corridor.

## Reporting Grain

Per Timepoint, Service Pattern, Day Part (not yet implemented), and Reporting Period (currently ad hoc for a week).

## Source Data

GTFS-Schedule and Trip Updates

In [1]:
import os
from sqlalchemy import create_engine
from jinja2 import Environment, FileSystemLoader
import pandas as pd
import geopandas as gpd
import shapely
import shapely.ops
import shapely.wkt

from src.data_loading import (
    get_matching_shapes_feeds,
    get_schedule_feed_entries,
    get_schedule_rt_stop_times,
)
from src.metric_calculation import calculate_travel_time_variability

### Parameters

In [2]:
TARGET_DATES = [
    "2026-06-15","2026-06-16","2026-06-17","2026-06-18","2026-06-19"
]
TARGET_ROUTE_SHORT_NAME = os.environ.get("TARGET_ROUTE_SHORT_NAME", "ECR")
TARGET_SCHEDULE_FEED = os.environ.get("TARGET_SCHEDULE_FEED", "Bay Area 511 SamTrans Schedule")
CONSTANT_MACROS = {
    "TARGET_DATES": TARGET_DATES,
    "TARGET_ROUTE_SHORT_NAME": TARGET_ROUTE_SHORT_NAME,
    "TARGET_SCHEDULE_FEED": TARGET_SCHEDULE_FEED
}
CONSTANT_MACROS

{'TARGET_DATES': ['2026-06-15',
  '2026-06-16',
  '2026-06-17',
  '2026-06-18',
  '2026-06-19'],
 'TARGET_ROUTE_SHORT_NAME': 'ECR',
 'TARGET_SCHEDULE_FEED': 'Bay Area 511 SamTrans Schedule'}

In [3]:
# min count of trips per service period to be considered reliable
MIN_TRIPS = 10

### Implementation

In [4]:
# gcp boilerplate
CALITP_BQ_MAX_BYTES = os.environ.get("CALITP_BQ_MAX_BYTES", 5_000_000_000)
CALITP_BQ_LOCATION = os.environ.get("CALITP_BQ_LOCATION", "us-west2")
engine = create_engine(
    f"bigquery://cal-itp-data-infra/?maximum_bytes_billed={CALITP_BQ_MAX_BYTES}",  # noqa: E231
    location=CALITP_BQ_LOCATION
)
env = Environment(loader=FileSystemLoader("templates"))

In [5]:
# Get the target route's service patterns, their geometry, and the feeds behind them
matching_shapes, feed_dates, feed_keys = get_matching_shapes_feeds(
    engine, env, CONSTANT_MACROS, min_trips=MIN_TRIPS
)
display(feed_dates)
matching_shapes

  service_date                          feed_key
0   2026-06-15  4dfefaf518766d1cfc3d254a65e4295e
1   2026-06-18  d71492afe126cd61f629b17c3c056fcd
2   2026-06-17  d71492afe126cd61f629b17c3c056fcd
4   2026-06-16  d71492afe126cd61f629b17c3c056fcd
5   2026-06-19  d71492afe126cd61f629b17c3c056fcd

,feed_key,last_seen_date,gtfs_dataset_name,shape_id,route_id,route_short_name,ct,geometry
0,4dfefaf518766d1cfc3d254a65e4295e,2026-06-15,Bay Area 511 SamTrans Schedule,ECR2069,ECR,ECR,350,"LINESTRING (-122.16599 37.44395, -122.16578 37..."
1,4dfefaf518766d1cfc3d254a65e4295e,2026-06-15,Bay Area 511 SamTrans Schedule,ECR2068,ECR,ECR,350,"LINESTRING (-122.46879 37.70620, -122.46897 37..."
2,d71492afe126cd61f629b17c3c056fcd,2026-06-19,Bay Area 511 SamTrans Schedule,ECR2069,ECR,ECR,350,"LINESTRING (-122.16599 37.44395, -122.16578 37..."
3,d71492afe126cd61f629b17c3c056fcd,2026-06-19,Bay Area 511 SamTrans Schedule,ECR2068,ECR,ECR,350,"LINESTRING (-122.46879 37.70620, -122.46897 37..."

In [6]:
# Get the schedule feed entry for every feed that was active during the window
feed_dates = get_schedule_feed_entries(engine, env, feed_dates)
feed_dates

,service_date,feed_key,base64_url,_valid_from
0,2026-06-15,4dfefaf518766d1cfc3d254a65e4295e,aHR0cHM6Ly9hcGkuNTExLm9yZy90cmFuc2l0L2RhdGFmZW...,2026-05-16 03:00:00.573378+00:00
1,2026-06-18,d71492afe126cd61f629b17c3c056fcd,aHR0cHM6Ly9hcGkuNTExLm9yZy90cmFuc2l0L2RhdGFmZW...,2026-06-16 03:00:00.395507+00:00
2,2026-06-17,d71492afe126cd61f629b17c3c056fcd,aHR0cHM6Ly9hcGkuNTExLm9yZy90cmFuc2l0L2RhdGFmZW...,2026-06-16 03:00:00.395507+00:00
3,2026-06-16,d71492afe126cd61f629b17c3c056fcd,aHR0cHM6Ly9hcGkuNTExLm9yZy90cmFuc2l0L2RhdGFmZW...,2026-06-16 03:00:00.395507+00:00
4,2026-06-19,d71492afe126cd61f629b17c3c056fcd,aHR0cHM6Ly9hcGkuNTExLm9yZy90cmFuc2l0L2RhdGFmZW...,2026-06-16 03:00:00.395507+00:00

In [7]:
# Get timepoint stops and schedule rt stop times for every selected date
schedule_rt_stop_times = get_schedule_rt_stop_times(
    engine,
    env,
    CONSTANT_MACROS,
    feed_dates=feed_dates,
    shape_ids=matching_shapes.shape_id.to_list(),
)

In [8]:
# Get times between stops and calculate the variance metric
# trips from every selected date are pooled into a single sample per segment
output_time_difference_variance = calculate_travel_time_variability(
    schedule_rt_stop_times
)

### Results

In [9]:
# Total rt stop arrivals per day
# note fewer stop arrivals on start and end of the week
schedule_rt_stop_times["actual_arrival_pacific"].dt.date.value_counts()

actual_arrival_pacific
2026-06-17    4575
2026-06-18    4504
2026-06-16    4477
2026-06-15    1376
2026-06-19       1
Name: count, dtype: int64

In [10]:
# Validity dates of different shapes, keyed by shape_id + feed_key
shape_date_validity = (
    schedule_rt_stop_times
    .groupby(["shape_id", "feed_key"])
    .agg(
        first_service_date=("service_date", "min"),
        last_service_date=("service_date", "max"),
        n_service_dates=("service_date", "nunique"),
        service_dates=(
            "service_date",
            lambda dates: ", ".join(map(str, sorted(dates.unique()))),
        ),
    )
)
# trip_id is only unique within a service date
shape_date_validity["n_rt_trips"] = (
    schedule_rt_stop_times[["shape_id", "feed_key", "service_date", "trip_id"]]
    .drop_duplicates()
    .groupby("shape_id")
    .size()
)
# where this is False the shape only ran for part of the window, so its map and its
# metrics are pooled over fewer days than the other shapes'
shape_date_validity["covers_all_target_dates"] = (
    shape_date_validity["n_service_dates"] == len(TARGET_DATES)
)
shape_date_validity = shape_date_validity.reset_index()
shape_date_validity

,shape_id,feed_key,first_service_date,last_service_date,n_service_dates,service_dates,n_rt_trips,covers_all_target_dates
0,ECR2068,4dfefaf518766d1cfc3d254a65e4295e,2026-06-15,2026-06-15,1,2026-06-15,NaN,False
1,ECR2068,d71492afe126cd61f629b17c3c056fcd,2026-06-16,2026-06-18,3,"2026-06-16, 2026-06-17, 2026-06-18",NaN,False
2,ECR2069,4dfefaf518766d1cfc3d254a65e4295e,2026-06-15,2026-06-15,1,2026-06-15,NaN,False
3,ECR2069,d71492afe126cd61f629b17c3c056fcd,2026-06-16,2026-06-18,3,"2026-06-16, 2026-06-17, 2026-06-18",NaN,False

In [11]:
# Time variance metric per segment
output_time_difference_variance

,shape_id,feed_key,stop_sequence,travel_time_variability,p80_travel_time_seconds,p20_travel_time_seconds,n_rt_trips,n_service_dates
0,ECR2068,4dfefaf518766d1cfc3d254a65e4295e,1,NaN,NaN,NaN,4,1
1,ECR2068,4dfefaf518766d1cfc3d254a65e4295e,2,2.401786,161.4,67.2,14,1
2,ECR2068,4dfefaf518766d1cfc3d254a65e4295e,5,1.339713,168.0,125.4,17,1
3,ECR2068,4dfefaf518766d1cfc3d254a65e4295e,8,1.395858,471.8,338.0,18,1
4,ECR2068,4dfefaf518766d1cfc3d254a65e4295e,13,1.393939,414.0,297.0,19,1
...,...,...,...,...,...,...,...,...
129,ECR2069,d71492afe126cd61f629b17c3c056fcd,62,1.863636,205.0,110.0,206,3
130,ECR2069,d71492afe126cd61f629b17c3c056fcd,68,1.493573,581.0,389.0,207,3
131,ECR2069,d71492afe126cd61f629b17c3c056fcd,71,1.882353,384.0,204.0,205,3
132,ECR2069,d71492afe126cd61f629b17c3c056fcd,74,2.089209,290.4,139.0,203,3
133,ECR2069,d71492afe126cd61f629b17c3c056fcd,75,1.695035,239.0,141.0,198,3

In [ ]:
# Maps of each segment

# Get a gdf of stops
timepoints = schedule_rt_stop_times[["shape_id", "feed_key", "stop_sequence", "stop_id", "pt_geom"]].drop_duplicates()
timepoints_gdf = gpd.GeoDataFrame(
    timepoints.drop(["pt_geom"], axis=1), 
    geometry=gpd.GeoSeries(timepoints["pt_geom"].map(shapely.wkt.loads), crs=4326)
)

for shape_id, feed_key, shape_geom in matching_shapes[["shape_id", "feed_key", "geometry"]].itertuples(index=False):
    timepoints_for_shape = timepoints_gdf.loc[
        (timepoints_gdf.shape_id == shape_id)
        & (timepoints_gdf.feed_key == feed_key)
    ].copy()
    timepoints_for_shape["projected_distance"] = timepoints_for_shape.geometry.map(
        lambda point_geom: shape_geom.project(point_geom)
    )
    timepoints_for_shape["prior_projected_distance"] = timepoints_for_shape["projected_distance"].shift()
    timepoints_for_shape["segment_geometry"] = timepoints_for_shape[["projected_distance", "prior_projected_distance"]].apply(
        lambda row: (
            shapely.ops.substring(shape_geom, row["projected_distance"], row["prior_projected_distance"])
            if not row.isna().any()
            else None
        ),
        axis=1
    )
    segment_geometry_with_values = (
        timepoints_for_shape
        .set_geometry("segment_geometry")
        [
            ["shape_id", "feed_key", "stop_sequence", "stop_id", "segment_geometry"]
        ]
        .merge(
            output_time_difference_variance,
            on=["shape_id", "feed_key", "stop_sequence"],
            how="left"
        )
    )
    segment_geometry_with_values = segment_geometry_with_values.loc[
        segment_geometry_with_values.stop_sequence != 2, #TODO: there seems to be an issue where this segment overlaps the entire route, so I've manually removed it
    ]
    segment_geometry_with_values.set_crs(4326).explore(
        "travel_time_variability",
        tiles="CartoDB positron"
    ).save(f"{shape_id}_{feed_key}.html")