# Segment delay breakdown (MIT thesis §3.3)

(this was an attempt to one-shot the intersection delay analysis - it really didn't work, but was usefrul for figuring out some initial challenges - e.g. stops recorded just after signal bars are hard, bus speeds relatively rarely go to 0, may need to use some more probabalistic modeling as suggested in the paper to calculate)

For each signal-bounded segment and each daytime trip, decompose observed travel time (Eq 3.6):

`T_obs = T_ff + T_dwell + D_signal + D_congestion + Loss`

- **Segments** run between consecutive signals; segments that END at a near-side signal are ignored.
- **T_ff** (free-flow) = 5th-percentile travel time of nighttime trips (start 21:00–06:00).
- **T_dwell**: stops near a bus stop or near-side signal are treated as dwell and excluded from signal/congestion.
- **D_signal = uniform + overflow**, measured from stop durations: the stop closest to the downstream signal (within 100 m) is uniform, capped at the red-phase length (95th-pct of night stop-bar stops); additional upstream stops within 200 m connected by creeping (stop-slow-stop, no faster period) are overflow.
- **D_congestion**: residual (Eq 3.21) = max(0, T_obs − T_ff − T_dwell − D_signal). Loss is neglected.

All calculations live in `segment_delay.py`; tunable parameters (night window, percentiles, signal-stop area, faster-period speed) are module constants there.

In [1]:
import geopandas as gpd
import pandas as pd
from IPython.display import display

from constants import CA_NAD83_Albers, CULVER_CITY_FEED_KEY, SERVICE_DATE, SHAPE_KEY_TO_SHAPE_ID_MAP
from _data_loaders import (
    get_culver_city_vehicle_positions,
    get_selected_shapes,
    get_traffic_signals,
    list_available_service_dates,
)
from segment_delay import run_segment_delay_analysis

## Configuration

In [2]:
SHAPE_KEY = "105"
SHAPE_ID = SHAPE_KEY_TO_SHAPE_ID_MAP[SHAPE_KEY]
print(f"Shape: {SHAPE_KEY} -> {SHAPE_ID}")

Shape: 105 -> shp-1-05

## Load inputs

All trips for the shape across every service date, plus the shape geometry, signals, and stops (with hand-curated near-side flags). Loading all dates reads every per-date geoparquet, so this cell is the slow one.

In [3]:
service_dates = list_available_service_dates()
vehicle_positions = pd.concat(
    [
        get_culver_city_vehicle_positions([SHAPE_KEY], service_date).assign(service_date=service_date)
        for service_date in service_dates
    ],
    ignore_index=True,
)
print(f"{len(vehicle_positions):,} positions over {len(service_dates)} dates")

shapes = get_selected_shapes(SERVICE_DATE, CULVER_CITY_FEED_KEY, [SHAPE_ID])
signals = get_traffic_signals()
stops = gpd.read_file(f"data/stops_{SHAPE_ID}.geojson").to_crs(CA_NAD83_Albers)

293,339 positions over 22 dates

## Run the breakdown

In [4]:
result = run_segment_delay_analysis(vehicle_positions, shapes, signals, stops, SHAPE_ID)
print(f"{len(result.segments)} analyzed segments (between signals, not ending at a near-side signal)")
result.segments.round(1)

44 analyzed segments (between signals, not ending at a near-side signal)

,start_signal,end_signal,start_distance_m,end_distance_m,length_m
segment_id,,,,,
sig1_to_sig2,1,2,27.5,386.5,359.0
sig2_to_sig3,2,3,386.5,517.1,130.5
sig3_to_sig4,3,4,517.1,981.9,464.8
sig4_to_sig5,4,5,981.9,1030.1,48.2
sig5_to_sig6,5,6,1030.1,1236.4,206.4
sig6_to_sig7,6,7,1236.4,1494.1,257.7
sig7_to_sig8,7,8,1494.1,1694.7,200.6
sig8_to_sig9,8,9,1694.7,1803.6,108.9
sig9_to_sig10,9,10,1803.6,2010.9,207.3
sig10_to_sig11,10,11,2010.9,2240.3,229.4
sig11_to_sig12,11,12,2240.3,2504.4,264.1
sig12_to_sig13,12,13,2504.4,2610.8,106.4
sig13_to_sig14,13,14,2610.8,2750.3,139.4
sig14_to_sig15,14,15,2750.3,2871.2,120.9
sig15_to_sig16,15,16,2871.2,2943.8,72.5
sig16_to_sig17,16,17,2943.8,2988.9,45.1
sig20_to_sig21,20,21,3557.0,3791.2,234.2
sig22_to_sig23,22,23,4122.3,4248.0,125.7
sig23_to_sig24,23,24,4248.0,4589.0,341.0
sig24_to_sig25,24,25,4589.0,4636.9,47.9
sig25_to_sig26,25,26,4636.9,4939.5,302.6
sig26_to_sig27,26,27,4939.5,5044.6,105.1
sig27_to_sig28,27,28,5044.6,5136.9,92.3
sig28_to_sig29,28,29,5136.9,5411.7,274.8
sig29_to_sig30,29,30,5411.7,5785.8,374.1
sig30_to_sig31,30,31,5785.8,6149.4,363.6
sig31_to_sig32,31,32,6149.4,6354.0,204.6
sig32_to_sig33,32,33,6354.0,6865.7,511.6
sig33_to_sig34,33,34,6865.7,7180.9,315.2
sig34_to_sig35,34,35,7180.9,7456.2,275.3
sig36_to_sig54,36,54,8033.6,8071.8,38.2
sig54_to_sig37,54,37,8071.8,8183.3,111.5
sig38_to_sig39,38,39,8417.3,8864.2,446.8
sig39_to_sig40,39,40,8864.2,9123.9,259.7
sig40_to_sig41,40,41,9123.9,9285.3,161.5
sig41_to_sig42,41,42,9285.3,9449.3,164.0
sig42_to_sig43,42,43,9449.3,9923.0,473.7
sig44_to_sig45,44,45,10236.7,10283.7,47.0
sig45_to_sig46,45,46,10283.7,10962.4,678.7
sig47_to_sig48,47,48,11250.1,11497.8,247.8
sig48_to_sig49,48,49,11497.8,11920.8,422.9
sig49_to_sig50,49,50,11920.8,12135.9,215.1
sig51_to_sig52,51,52,12208.7,12409.7,200.9
sig52_to_sig53,52,53,12409.7,12564.1,154.5

## Trip numbers per segment

Daytime trips per segment: total, how many stopped at the signal, how many had overflow, how many had any congestion delay, plus the nighttime sample size behind each segment's baselines.

In [5]:
result.trip_counts

,n_day_trips,n_signal_stop,n_overflow,n_congestion,n_night_trips
segment_id,,,,,
sig1_to_sig2,549,0,0,517,45
sig2_to_sig3,670,13,9,656,57
sig3_to_sig4,671,0,0,645,57
sig4_to_sig5,671,5,0,651,57
sig5_to_sig6,671,1,0,650,57
sig6_to_sig7,672,0,0,658,57
sig7_to_sig8,673,1,0,640,57
sig8_to_sig9,673,19,0,635,57
sig9_to_sig10,673,14,0,643,57
sig10_to_sig11,675,1,0,618,57
sig11_to_sig12,675,1,0,648,57
sig12_to_sig13,675,132,46,647,57
sig13_to_sig14,676,27,4,599,57
sig14_to_sig15,679,29,5,620,58
sig15_to_sig16,680,64,29,584,58
sig16_to_sig17,683,66,24,588,58
sig20_to_sig21,694,5,0,677,58
sig22_to_sig23,697,181,65,686,58
sig23_to_sig24,698,0,0,685,58
sig24_to_sig25,699,2,0,689,58
sig25_to_sig26,699,5,0,693,58
sig26_to_sig27,700,4,0,689,58
sig27_to_sig28,700,1,0,690,58
sig28_to_sig29,700,17,0,685,58
sig29_to_sig30,700,1,0,656,58
sig30_to_sig31,701,0,0,695,58
sig31_to_sig32,701,2,0,695,58
sig32_to_sig33,701,5,0,687,58
sig33_to_sig34,701,0,0,693,58
sig34_to_sig35,701,22,0,700,58
sig36_to_sig54,701,17,0,667,58
sig54_to_sig37,701,79,0,660,58
sig38_to_sig39,701,10,0,700,58
sig39_to_sig40,701,9,0,690,58
sig40_to_sig41,701,9,0,697,58
sig41_to_sig42,700,19,1,696,58
sig42_to_sig43,699,1,0,691,58
sig44_to_sig45,697,0,0,686,58
sig45_to_sig46,697,1,0,679,58
sig47_to_sig48,697,7,0,695,58
sig48_to_sig49,697,0,0,692,58
sig49_to_sig50,697,0,0,685,58
sig51_to_sig52,696,1,0,661,58
sig52_to_sig53,696,1,0,633,58

## Raw travel times per segment

Descriptive statistics of observed daytime segment travel times (seconds), with the free-flow travel time (T_ff) alongside. The matrix below is one daytime trip per row, one segment per column.

In [6]:
display(result.raw_travel_times.round(1))
display(result.travel_time_matrix.round(1))

,count,mean,std,min,25%,50%,75%,max,free_flow_travel_time_s
segment_id,,,,,,,,,
sig10_to_sig11,675.0,45.1,17.8,18.2,32.1,41.6,53.6,133.8,26.9
sig11_to_sig12,675.0,54.5,28.3,18.4,35.9,48.0,66.5,360.8,26.4
sig12_to_sig13,675.0,40.0,25.1,10.9,21.6,32.9,51.0,167.5,13.7
sig13_to_sig14,676.0,43.5,23.9,12.9,25.8,37.4,52.7,143.5,20.8
sig14_to_sig15,679.0,46.0,25.7,10.6,28.0,38.5,58.7,235.9,19.4
sig15_to_sig16,680.0,32.6,22.9,6.1,17.9,27.6,39.5,199.4,13.1
sig16_to_sig17,683.0,19.0,13.2,3.4,11.0,15.5,23.5,88.3,6.8
sig1_to_sig2,549.0,50.8,23.8,19.8,37.7,46.5,58.8,412.9,23.8
sig20_to_sig21,694.0,41.9,50.5,12.6,20.0,25.8,37.7,511.9,14.8
sig22_to_sig23,697.0,65.9,38.1,6.7,33.6,64.3,90.6,278.7,10.1
sig23_to_sig24,698.0,57.4,31.1,17.0,39.7,51.8,68.5,406.5,24.0
sig24_to_sig25,699.0,7.9,5.2,2.7,4.5,6.5,9.4,59.4,3.0
sig25_to_sig26,699.0,52.0,27.0,16.4,31.7,47.3,64.5,300.4,19.7
sig26_to_sig27,700.0,18.7,11.5,5.6,11.0,15.9,23.0,102.7,6.6
sig27_to_sig28,700.0,14.8,7.3,4.9,9.4,13.2,18.0,52.3,5.4
sig28_to_sig29,700.0,46.4,21.2,16.6,34.0,42.7,52.5,212.4,20.6
sig29_to_sig30,700.0,102.2,42.7,29.4,67.2,99.1,129.3,284.1,41.0
sig2_to_sig3,670.0,23.6,16.0,6.9,12.5,18.9,29.9,113.9,7.8
sig30_to_sig31,701.0,49.1,17.7,17.6,37.2,45.7,57.2,149.1,21.5
sig31_to_sig32,701.0,30.8,15.0,12.0,19.5,29.2,37.7,154.4,12.9
sig32_to_sig33,701.0,69.0,22.0,32.8,55.0,64.8,77.9,179.1,37.8
sig33_to_sig34,701.0,74.3,34.3,16.6,50.0,64.4,93.2,230.6,23.3
sig34_to_sig35,701.0,62.2,31.0,17.7,42.6,55.2,71.8,310.6,20.5
sig36_to_sig54,701.0,17.3,25.3,2.1,4.3,5.9,14.1,127.3,2.8
sig38_to_sig39,701.0,81.0,65.2,28.2,45.9,59.8,82.5,500.4,28.7
sig39_to_sig40,701.0,75.7,48.2,16.9,41.7,60.2,95.4,304.4,17.2
sig3_to_sig4,671.0,61.3,25.1,26.9,44.7,55.6,70.0,210.4,32.5
sig40_to_sig41,701.0,55.0,71.0,11.4,31.1,46.1,65.2,1747.0,12.1
sig41_to_sig42,700.0,66.0,31.0,10.6,42.3,65.0,84.5,220.7,14.5
sig42_to_sig43,699.0,107.5,41.4,34.4,78.9,98.5,128.6,366.0,41.3
sig44_to_sig45,697.0,5.7,2.5,2.2,3.8,5.1,7.0,19.4,2.8
sig45_to_sig46,697.0,74.0,23.9,33.6,58.3,70.8,84.9,407.5,43.3
sig47_to_sig48,697.0,52.5,21.0,21.5,38.1,47.9,62.4,167.7,21.9
sig48_to_sig49,697.0,65.6,19.5,33.1,54.4,62.6,73.3,295.8,37.0
sig49_to_sig50,697.0,28.9,9.1,12.7,22.8,27.4,33.0,108.2,16.2
sig4_to_sig5,671.0,6.5,10.2,2.6,3.9,4.7,6.2,233.9,3.0
sig51_to_sig52,696.0,36.0,51.3,14.4,24.2,29.6,36.2,784.0,18.3
sig52_to_sig53,696.0,31.3,10.3,12.1,24.4,29.5,36.7,111.7,19.6
sig54_to_sig37,701.0,27.8,28.0,6.4,12.1,15.8,25.8,134.6,8.7
sig5_to_sig6,671.0,25.6,12.9,11.1,17.3,22.2,30.0,189.5,12.7
sig6_to_sig7,672.0,30.8,12.4,15.5,22.3,27.7,36.4,160.6,16.8
sig7_to_sig8,673.0,24.1,10.9,12.3,17.9,21.1,27.6,149.1,15.0
sig8_to_sig9,673.0,18.1,11.8,6.4,10.8,14.4,20.6,79.0,8.4
sig9_to_sig10,673.0,65.9,29.1,17.1,44.7,59.7,80.9,236.4,30.4

segment_id             sig10_to_sig11  sig11_to_sig12  sig12_to_sig13  \
service_date TRIP_KEY
2026-01-31   1016.0              49.4            29.5            39.2
             1053.0              24.9            51.8            38.8
             1068.0              37.8            41.9            23.4
             1089.0              31.6            41.8            98.6
             1156.0              81.9            72.9            60.0
...                               ...             ...             ...
2026-02-16   858.0               27.7            41.7            30.6
             876.0               28.5            34.1            38.5
             943.0               61.7            74.4            29.4
             972.0               37.8            30.3            18.2
             986.0               56.7            53.3            87.9

segment_id             sig13_to_sig14  sig14_to_sig15  sig15_to_sig16  \
service_date TRIP_KEY
2026-01-31   1016.0              31.1            38.3            20.9
             1053.0              87.3            71.6            23.4
             1068.0              23.7            33.0            21.0
             1089.0              42.8            31.4            13.1
             1156.0              54.2            45.0            43.1
...                               ...             ...             ...
2026-02-16   858.0              138.5            16.9            18.7
             876.0              103.9            45.5            14.8
             943.0               21.2            24.3            52.2
             972.0               61.6            40.5            13.2
             986.0               86.0            51.4            39.3

segment_id             sig16_to_sig17  sig1_to_sig2  sig20_to_sig21  \
service_date TRIP_KEY
2026-01-31   1016.0              11.9          37.7            53.6
             1053.0              10.4          49.4            22.2
             1068.0               8.7          38.8            19.7
             1089.0               5.0          79.7           253.8
             1156.0              44.2          48.7            30.6
...                               ...           ...             ...
2026-02-16   858.0               87.5          55.9            20.4
             876.0                7.9          27.2            22.3
             943.0               22.7          43.7            22.9
             972.0                7.7          48.9            35.7
             986.0               29.8          90.1            18.7

segment_id             sig22_to_sig23  ...  sig49_to_sig50  sig4_to_sig5  \
service_date TRIP_KEY                  ...
2026-01-31   1016.0              16.6  ...            39.8           3.0
             1053.0             100.0  ...            43.5           4.9
             1068.0              76.9  ...            67.2           6.0
             1089.0              25.1  ...            31.9           3.6
             1156.0             119.6  ...            41.9           5.8
...                               ...  ...             ...           ...
2026-02-16   858.0               69.4  ...            17.7           5.6
             876.0               19.8  ...            18.9           3.5
             943.0               89.2  ...            27.9           3.5
             972.0               41.1  ...            19.3           5.1
             986.0               11.0  ...            22.9           4.7

segment_id             sig51_to_sig52  sig52_to_sig53  sig54_to_sig37  \
service_date TRIP_KEY
2026-01-31   1016.0              41.2            38.3            15.4
             1053.0              48.0            35.5            12.4
             1068.0              72.0            82.2             8.3
             1089.0              39.4            49.5            39.5
             1156.0              48.1            50.5            82.3
...                               ...             ...             ...
2026-02-16   858.0               20.9            27.0            18.1
             876.0               20.0            20.7            12.5
             943.0               34.2            36.7            29.4
             972.0               20.7            18.5            13.9
             986.0               21.7            18.3            26.4

segment_id             sig5_to_sig6  sig6_to_sig7  sig7_to_sig8  sig8_to_sig9  \
service_date TRIP_KEY
2026-01-31   1016.0            12.4          20.6          30.0          16.9
             1053.0            23.8          50.7          15.2           8.9
             1068.0            32.1          29.5          18.7          11.4
             1089.0            14.0          20.4          54.5          25.3
             1156.0            28.6          47.1          37.9          23.5
...                             ...           ...           ...           ...
2026-02-16   858.0             22.7          26.9          20.7          11.4
             876.0             12.8          17.6          15.5          15.2
             943.0             16.9          24.0          22.9          50.7
             972.0             28.2          34.2          18.6          16.0
             986.0             20.3          26.1          28.2          22.4

segment_id             sig9_to_sig10
service_date TRIP_KEY
2026-01-31   1016.0             89.3
             1053.0             41.8
             1068.0             63.8
             1089.0             63.7
             1156.0             46.1
...                              ...
2026-02-16   858.0              22.6
             876.0              58.4
             943.0              50.4
             972.0              66.4
             986.0              79.6

[702 rows x 44 columns]

## Delays per segment

Descriptive statistics (seconds) of each delay component over daytime trips: uniform, overflow, total signal, and congestion delay.

In [7]:
for component in ["uniform_delay_s", "overflow_delay_s", "signal_delay_s", "congestion_delay_s"]:
    print(f"{component} by segment:")
    display(result.component_stats[component].round(1))

uniform_delay_s by segment:

                count  mean   std  min  25%  50%   75%    max
segment_id
sig10_to_sig11  675.0   0.0   0.2  0.0  0.0  0.0   0.0    6.0
sig11_to_sig12  675.0   0.0   1.1  0.0  0.0  0.0   0.0   28.0
sig12_to_sig13  675.0   4.3   9.7  0.0  0.0  0.0   0.0   32.6
sig13_to_sig14  676.0   1.1   7.3  0.0  0.0  0.0   0.0  109.0
sig14_to_sig15  679.0   0.9   4.8  0.0  0.0  0.0   0.0   39.8
sig15_to_sig16  680.0   2.4   8.0  0.0  0.0  0.0   0.0   35.3
sig16_to_sig17  683.0   4.1  13.5  0.0  0.0  0.0   0.0   58.6
sig1_to_sig2    549.0   0.0   0.0  0.0  0.0  0.0   0.0    0.0
sig20_to_sig21  694.0   0.5   9.4  0.0  0.0  0.0   0.0  201.0
sig22_to_sig23  697.0  11.2  20.9  0.0  0.0  0.0  10.0   59.5
sig23_to_sig24  698.0   0.0   0.0  0.0  0.0  0.0   0.0    0.0
sig24_to_sig25  699.0   0.5  11.9  0.0  0.0  0.0   0.0  314.0
sig25_to_sig26  699.0   0.5   9.0  0.0  0.0  0.0   0.0  221.0
sig26_to_sig27  700.0   0.2   2.7  0.0  0.0  0.0   0.0   52.0
sig27_to_sig28  700.0   0.0   1.2  0.0  0.0  0.0   0.0   32.0
sig28_to_sig29  700.0   0.9   6.9  0.0  0.0  0.0   0.0  112.0
sig29_to_sig30  700.0   0.1   1.6  0.0  0.0  0.0   0.0   43.0
sig2_to_sig3    670.0   0.3   2.0  0.0  0.0  0.0   0.0   16.0
sig30_to_sig31  701.0   0.0   0.0  0.0  0.0  0.0   0.0    0.0
sig31_to_sig32  701.0   0.0   0.6  0.0  0.0  0.0   0.0   15.0
sig32_to_sig33  701.0   0.2   2.7  0.0  0.0  0.0   0.0   54.0
sig33_to_sig34  701.0   0.0   0.0  0.0  0.0  0.0   0.0    0.0
sig34_to_sig35  701.0   1.2   8.1  0.0  0.0  0.0   0.0  115.0
sig36_to_sig54  701.0   1.7  11.8  0.0  0.0  0.0   0.0  114.0
sig38_to_sig39  701.0   1.1  11.3  0.0  0.0  0.0   0.0  166.0
sig39_to_sig40  701.0   0.6   5.8  0.0  0.0  0.0   0.0   84.0
sig3_to_sig4    671.0   0.0   0.0  0.0  0.0  0.0   0.0    0.0
sig40_to_sig41  701.0   0.5   4.8  0.0  0.0  0.0   0.0   81.0
sig41_to_sig42  700.0   1.1   9.5  0.0  0.0  0.0   0.0  147.0
sig42_to_sig43  699.0   0.0   0.3  0.0  0.0  0.0   0.0    8.0
sig44_to_sig45  697.0   0.0   0.0  0.0  0.0  0.0   0.0    0.0
sig45_to_sig46  697.0   0.5  13.0  0.0  0.0  0.0   0.0  343.0
sig47_to_sig48  697.0   0.2   2.3  0.0  0.0  0.0   0.0   36.0
sig48_to_sig49  697.0   0.0   0.0  0.0  0.0  0.0   0.0    0.0
sig49_to_sig50  697.0   0.0   0.0  0.0  0.0  0.0   0.0    0.0
sig4_to_sig5    671.0   0.2   1.9  0.0  0.0  0.0   0.0   32.0
sig51_to_sig52  696.0   0.4   9.7  0.0  0.0  0.0   0.0  256.0
sig52_to_sig53  696.0   0.0   0.4  0.0  0.0  0.0   0.0   11.0
sig54_to_sig37  701.0   7.7  23.4  0.0  0.0  0.0   0.0  113.0
sig5_to_sig6    671.0   0.2   5.6  0.0  0.0  0.0   0.0  145.0
sig6_to_sig7    672.0   0.0   0.0  0.0  0.0  0.0   0.0    0.0
sig7_to_sig8    673.0   0.1   2.0  0.0  0.0  0.0   0.0   52.0
sig8_to_sig9    673.0   0.5   2.9  0.0  0.0  0.0   0.0   29.0
sig9_to_sig10   673.0   0.5   3.7  0.0  0.0  0.0   0.0   61.0

overflow_delay_s by segment:

                count  mean   std  min  25%  50%  75%    max
segment_id
sig10_to_sig11  675.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig11_to_sig12  675.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig12_to_sig13  675.0   2.2  11.9  0.0  0.0  0.0  0.0  167.4
sig13_to_sig14  676.0   0.1   1.8  0.0  0.0  0.0  0.0   32.0
sig14_to_sig15  679.0   0.1   1.3  0.0  0.0  0.0  0.0   21.2
sig15_to_sig16  680.0   1.4  10.7  0.0  0.0  0.0  0.0  168.7
sig16_to_sig17  683.0   0.6   6.0  0.0  0.0  0.0  0.0  108.4
sig1_to_sig2    549.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig20_to_sig21  694.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig22_to_sig23  697.0   1.7   7.1  0.0  0.0  0.0  0.0   92.5
sig23_to_sig24  698.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig24_to_sig25  699.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig25_to_sig26  699.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig26_to_sig27  700.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig27_to_sig28  700.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig28_to_sig29  700.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig29_to_sig30  700.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig2_to_sig3    670.0   0.2   2.3  0.0  0.0  0.0  0.0   30.0
sig30_to_sig31  701.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig31_to_sig32  701.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig32_to_sig33  701.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig33_to_sig34  701.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig34_to_sig35  701.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig36_to_sig54  701.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig38_to_sig39  701.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig39_to_sig40  701.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig3_to_sig4    671.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig40_to_sig41  701.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig41_to_sig42  700.0   0.0   0.6  0.0  0.0  0.0  0.0   15.0
sig42_to_sig43  699.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig44_to_sig45  697.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig45_to_sig46  697.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig47_to_sig48  697.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig48_to_sig49  697.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig49_to_sig50  697.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig4_to_sig5    671.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig51_to_sig52  696.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig52_to_sig53  696.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig54_to_sig37  701.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig5_to_sig6    671.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig6_to_sig7    672.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig7_to_sig8    673.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig8_to_sig9    673.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0
sig9_to_sig10   673.0   0.0   0.0  0.0  0.0  0.0  0.0    0.0

signal_delay_s by segment:

                count  mean   std  min  25%  50%   75%    max
segment_id
sig10_to_sig11  675.0   0.0   0.2  0.0  0.0  0.0   0.0    6.0
sig11_to_sig12  675.0   0.0   1.1  0.0  0.0  0.0   0.0   28.0
sig12_to_sig13  675.0   6.5  18.7  0.0  0.0  0.0   0.0  200.0
sig13_to_sig14  676.0   1.2   7.7  0.0  0.0  0.0   0.0  109.0
sig14_to_sig15  679.0   1.0   5.5  0.0  0.0  0.0   0.0   61.0
sig15_to_sig16  680.0   3.7  16.4  0.0  0.0  0.0   0.0  204.0
sig16_to_sig17  683.0   4.7  16.8  0.0  0.0  0.0   0.0  167.0
sig1_to_sig2    549.0   0.0   0.0  0.0  0.0  0.0   0.0    0.0
sig20_to_sig21  694.0   0.5   9.4  0.0  0.0  0.0   0.0  201.0
sig22_to_sig23  697.0  12.9  25.5  0.0  0.0  0.0  10.0  152.0
sig23_to_sig24  698.0   0.0   0.0  0.0  0.0  0.0   0.0    0.0
sig24_to_sig25  699.0   0.5  11.9  0.0  0.0  0.0   0.0  314.0
sig25_to_sig26  699.0   0.5   9.0  0.0  0.0  0.0   0.0  221.0
sig26_to_sig27  700.0   0.2   2.7  0.0  0.0  0.0   0.0   52.0
sig27_to_sig28  700.0   0.0   1.2  0.0  0.0  0.0   0.0   32.0
sig28_to_sig29  700.0   0.9   6.9  0.0  0.0  0.0   0.0  112.0
sig29_to_sig30  700.0   0.1   1.6  0.0  0.0  0.0   0.0   43.0
sig2_to_sig3    670.0   0.5   4.1  0.0  0.0  0.0   0.0   46.0
sig30_to_sig31  701.0   0.0   0.0  0.0  0.0  0.0   0.0    0.0
sig31_to_sig32  701.0   0.0   0.6  0.0  0.0  0.0   0.0   15.0
sig32_to_sig33  701.0   0.2   2.7  0.0  0.0  0.0   0.0   54.0
sig33_to_sig34  701.0   0.0   0.0  0.0  0.0  0.0   0.0    0.0
sig34_to_sig35  701.0   1.2   8.1  0.0  0.0  0.0   0.0  115.0
sig36_to_sig54  701.0   1.7  11.8  0.0  0.0  0.0   0.0  114.0
sig38_to_sig39  701.0   1.1  11.3  0.0  0.0  0.0   0.0  166.0
sig39_to_sig40  701.0   0.6   5.8  0.0  0.0  0.0   0.0   84.0
sig3_to_sig4    671.0   0.0   0.0  0.0  0.0  0.0   0.0    0.0
sig40_to_sig41  701.0   0.5   4.8  0.0  0.0  0.0   0.0   81.0
sig41_to_sig42  700.0   1.2   9.5  0.0  0.0  0.0   0.0  147.0
sig42_to_sig43  699.0   0.0   0.3  0.0  0.0  0.0   0.0    8.0
sig44_to_sig45  697.0   0.0   0.0  0.0  0.0  0.0   0.0    0.0
sig45_to_sig46  697.0   0.5  13.0  0.0  0.0  0.0   0.0  343.0
sig47_to_sig48  697.0   0.2   2.3  0.0  0.0  0.0   0.0   36.0
sig48_to_sig49  697.0   0.0   0.0  0.0  0.0  0.0   0.0    0.0
sig49_to_sig50  697.0   0.0   0.0  0.0  0.0  0.0   0.0    0.0
sig4_to_sig5    671.0   0.2   1.9  0.0  0.0  0.0   0.0   32.0
sig51_to_sig52  696.0   0.4   9.7  0.0  0.0  0.0   0.0  256.0
sig52_to_sig53  696.0   0.0   0.4  0.0  0.0  0.0   0.0   11.0
sig54_to_sig37  701.0   7.7  23.4  0.0  0.0  0.0   0.0  113.0
sig5_to_sig6    671.0   0.2   5.6  0.0  0.0  0.0   0.0  145.0
sig6_to_sig7    672.0   0.0   0.0  0.0  0.0  0.0   0.0    0.0
sig7_to_sig8    673.0   0.1   2.0  0.0  0.0  0.0   0.0   52.0
sig8_to_sig9    673.0   0.5   2.9  0.0  0.0  0.0   0.0   29.0
sig9_to_sig10   673.0   0.5   3.7  0.0  0.0  0.0   0.0   61.0

congestion_delay_s by segment:

                count  mean   std  min   25%   50%   75%     max
segment_id
sig10_to_sig11  675.0  18.1  17.1  0.0   5.1  14.2  26.3   106.9
sig11_to_sig12  675.0  26.2  22.3  0.0   9.5  21.4  38.7   182.9
sig12_to_sig13  675.0  19.3  14.3  0.0   7.2  18.1  28.5    74.9
sig13_to_sig14  676.0  21.8  21.2  0.0   5.0  16.5  31.4   122.6
sig14_to_sig15  679.0  23.1  19.3  0.0   8.4  18.2  34.6   133.8
sig15_to_sig16  680.0  16.4  15.8  0.0   4.6  14.1  23.8   169.5
sig16_to_sig17  683.0   9.1   8.3  0.0   2.6   7.3  13.8    56.9
sig1_to_sig2    549.0  24.9  23.5  0.0  12.6  21.6  32.6   389.1
sig20_to_sig21  694.0  22.3  40.6  0.0   5.0  10.9  21.5   497.1
sig22_to_sig23  697.0  28.3  15.4  0.0  17.1  26.8  38.8    73.0
sig23_to_sig24  698.0  32.4  29.3  0.0  15.6  27.5  43.9   382.4
sig24_to_sig25  699.0   4.8   4.6  0.0   1.5   3.5   6.3    28.4
sig25_to_sig26  699.0  31.7  24.6  0.0  12.0  27.6  44.8   147.1
sig26_to_sig27  700.0  12.0  10.7  0.0   4.4   9.3  16.4    76.7
sig27_to_sig28  700.0   9.3   7.3  0.0   4.0   7.8  12.5    46.9
sig28_to_sig29  700.0  24.9  19.2  0.0  13.4  22.1  31.3   170.8
sig29_to_sig30  700.0  44.9  35.3  0.0  17.4  38.9  65.3   213.5
sig2_to_sig3    670.0  14.3  12.2  0.0   4.7  11.1  21.5    67.1
sig30_to_sig31  701.0  26.9  16.3  0.0  15.7  24.2  35.0    83.3
sig31_to_sig32  701.0  17.8  14.6  0.0   6.7  16.4  24.8   141.6
sig32_to_sig33  701.0  30.2  19.4  0.0  17.2  27.0  39.6   124.7
sig33_to_sig34  701.0  43.8  27.6  0.0  25.9  38.5  55.1   207.3
sig34_to_sig35  701.0  37.8  24.9  0.0  21.5  33.4  47.5   290.1
sig36_to_sig54  701.0   7.7  14.0  0.0   1.4   2.9   8.8   104.7
sig38_to_sig39  701.0  46.7  50.0  0.0  17.3  31.0  51.5   341.1
sig39_to_sig40  701.0  50.8  38.8  0.0  23.5  40.8  70.2   287.2
sig3_to_sig4    671.0  28.4  23.7  0.0  12.2  23.1  37.5   177.9
sig40_to_sig41  701.0  39.1  68.4  0.0  18.9  33.1  50.7  1735.0
sig41_to_sig42  700.0  47.7  26.0  0.0  27.8  47.4  66.1   165.1
sig42_to_sig43  699.0  59.1  34.8  0.0  35.5  53.2  77.3   260.6
sig44_to_sig45  697.0   3.0   2.5  0.0   1.0   2.3   4.3    16.6
sig45_to_sig46  697.0  30.3  20.2  0.0  15.0  27.3  41.5   112.2
sig47_to_sig48  697.0  29.5  18.5  0.0  16.2  25.8  40.1   117.8
sig48_to_sig49  697.0  28.6  19.5  0.0  17.4  25.6  36.3   258.9
sig49_to_sig50  697.0  12.7   9.1  0.0   6.7  11.2  16.8    92.1
sig4_to_sig5    671.0   3.3   9.8  0.0   0.9   1.6   3.2   230.9
sig51_to_sig52  696.0  13.4  11.3  0.0   5.9  11.2  17.9   149.4
sig52_to_sig53  696.0  11.9  10.0  0.0   4.8   9.9  17.1    92.0
sig54_to_sig37  701.0  11.7  14.9  0.0   3.2   6.4  13.1   125.9
sig5_to_sig6    671.0  12.4  10.7  0.0   4.5   9.4  17.1    80.6
sig6_to_sig7    672.0  13.9  12.1  0.0   5.6  10.9  19.6   143.8
sig7_to_sig8    673.0   9.1  10.3  0.0   2.9   6.1  12.6   134.1
sig8_to_sig9    673.0   8.9   9.5  0.0   2.3   6.0  12.2    54.9
sig9_to_sig10   673.0  28.2  21.8  0.0  12.7  22.9  40.4   177.1

## Segment summary

One row per segment: geometry, free-flow time, red-phase cap, trip counts, and mean uniform / overflow / signal / congestion / dwell.

In [8]:
result.segment_summary.round(1)

,start_signal,end_signal,start_distance_m,end_distance_m,length_m,free_flow_travel_time_s,red_phase_cap_s,n_day_trips,n_signal_stop,n_overflow,n_congestion,n_night_trips,mean_uniform_delay_s,mean_overflow_delay_s,mean_signal_delay_s,mean_congestion_delay_s,mean_total_delay_s,mean_dwell_s
segment_id,,,,,,,,,,,,,,,,,,
sig1_to_sig2,1,2,27.5,386.5,359.0,23.8,NaN,549,0,0,517,45,0.0,0.0,0.0,24.9,24.9,3.9
sig2_to_sig3,2,3,386.5,517.1,130.5,7.8,16.0,670,13,9,656,57,0.3,0.2,0.5,14.3,14.9,0.9
sig3_to_sig4,3,4,517.1,981.9,464.8,32.5,NaN,671,0,0,645,57,0.0,0.0,0.0,28.4,28.4,0.5
sig4_to_sig5,4,5,981.9,1030.1,48.2,3.0,NaN,671,5,0,651,57,0.2,0.0,0.2,3.3,3.4,0.0
sig5_to_sig6,5,6,1030.1,1236.4,206.4,12.7,NaN,671,1,0,650,57,0.2,0.0,0.2,12.4,12.6,0.8
sig6_to_sig7,6,7,1236.4,1494.1,257.7,16.8,NaN,672,0,0,658,57,0.0,0.0,0.0,13.9,13.9,0.1
sig7_to_sig8,7,8,1494.1,1694.7,200.6,15.0,NaN,673,1,0,640,57,0.1,0.0,0.1,9.1,9.2,0.0
sig8_to_sig9,8,9,1694.7,1803.6,108.9,8.4,NaN,673,19,0,635,57,0.5,0.0,0.5,8.9,9.4,0.3
sig9_to_sig10,9,10,1803.6,2010.9,207.3,30.4,67.8,673,14,0,643,57,0.5,0.0,0.5,28.2,28.6,7.2
sig10_to_sig11,10,11,2010.9,2240.3,229.4,26.9,NaN,675,1,0,618,57,0.0,0.0,0.0,18.1,18.2,0.5
sig11_to_sig12,11,12,2240.3,2504.4,264.1,26.4,NaN,675,1,0,648,57,0.0,0.0,0.0,26.2,26.2,1.9
sig12_to_sig13,12,13,2504.4,2610.8,106.4,13.7,32.6,675,132,46,647,57,4.3,2.2,6.5,19.3,25.9,1.0
sig13_to_sig14,13,14,2610.8,2750.3,139.4,20.8,NaN,676,27,4,599,57,1.1,0.1,1.2,21.8,23.0,0.0
sig14_to_sig15,14,15,2750.3,2871.2,120.9,19.4,39.8,679,29,5,620,58,0.9,0.1,1.0,23.1,24.1,2.9
sig15_to_sig16,15,16,2871.2,2943.8,72.5,13.1,35.3,680,64,29,584,58,2.4,1.4,3.7,16.4,20.1,0.0
sig16_to_sig17,16,17,2943.8,2988.9,45.1,6.8,58.6,683,66,24,588,58,4.1,0.6,4.7,9.1,13.8,0.0
sig20_to_sig21,20,21,3557.0,3791.2,234.2,14.8,NaN,694,5,0,677,58,0.5,0.0,0.5,22.3,22.8,4.7
sig22_to_sig23,22,23,4122.3,4248.0,125.7,10.1,59.5,697,181,65,686,58,11.2,1.7,12.9,28.3,41.2,14.8
sig23_to_sig24,23,24,4248.0,4589.0,341.0,24.0,NaN,698,0,0,685,58,0.0,0.0,0.0,32.4,32.4,1.0
sig24_to_sig25,24,25,4589.0,4636.9,47.9,3.0,NaN,699,2,0,689,58,0.5,0.0,0.5,4.8,5.2,0.0
sig25_to_sig26,25,26,4636.9,4939.5,302.6,19.7,NaN,699,5,0,693,58,0.5,0.0,0.5,31.7,32.3,0.1
sig26_to_sig27,26,27,4939.5,5044.6,105.1,6.6,NaN,700,4,0,689,58,0.2,0.0,0.2,12.0,12.2,0.0
sig27_to_sig28,27,28,5044.6,5136.9,92.3,5.4,NaN,700,1,0,690,58,0.0,0.0,0.0,9.3,9.3,0.0
sig28_to_sig29,28,29,5136.9,5411.7,274.8,20.6,NaN,700,17,0,685,58,0.9,0.0,0.9,24.9,25.8,0.0
sig29_to_sig30,29,30,5411.7,5785.8,374.1,41.0,NaN,700,1,0,656,58,0.1,0.0,0.1,44.9,44.9,16.7
sig30_to_sig31,30,31,5785.8,6149.4,363.6,21.5,NaN,701,0,0,695,58,0.0,0.0,0.0,26.9,26.9,0.8
sig31_to_sig32,31,32,6149.4,6354.0,204.6,12.9,NaN,701,2,0,695,58,0.0,0.0,0.0,17.8,17.8,0.1
sig32_to_sig33,32,33,6354.0,6865.7,511.6,37.8,NaN,701,5,0,687,58,0.2,0.0,0.2,30.2,30.4,0.8
sig33_to_sig34,33,34,6865.7,7180.9,315.2,23.3,NaN,701,0,0,693,58,0.0,0.0,0.0,43.8,43.8,7.2
sig34_to_sig35,34,35,7180.9,7456.2,275.3,20.5,NaN,701,22,0,700,58,1.2,0.0,1.2,37.8,38.9,2.8
sig36_to_sig54,36,54,8033.6,8071.8,38.2,2.8,NaN,701,17,0,667,58,1.7,0.0,1.7,7.7,9.4,5.8
sig54_to_sig37,54,37,8071.8,8183.3,111.5,8.7,NaN,701,79,0,660,58,7.7,0.0,7.7,11.7,19.5,0.1
sig38_to_sig39,38,39,8417.3,8864.2,446.8,28.7,NaN,701,10,0,700,58,1.1,0.0,1.1,46.7,47.8,4.5
sig39_to_sig40,39,40,8864.2,9123.9,259.7,17.2,NaN,701,9,0,690,58,0.6,0.0,0.6,50.8,51.3,7.7
sig40_to_sig41,40,41,9123.9,9285.3,161.5,12.1,NaN,701,9,0,697,58,0.5,0.0,0.5,39.1,39.6,3.3
sig41_to_sig42,41,42,9285.3,9449.3,164.0,14.5,NaN,700,19,1,696,58,1.1,0.0,1.2,47.7,48.9,2.7
sig42_to_sig43,42,43,9449.3,9923.0,473.7,41.3,NaN,699,1,0,691,58,0.0,0.0,0.0,59.1,59.1,7.5
sig44_to_sig45,44,45,10236.7,10283.7,47.0,2.8,NaN,697,0,0,686,58,0.0,0.0,0.0,3.0,3.0,0.0
sig45_to_sig46,45,46,10283.7,10962.4,678.7,43.3,NaN,697,1,0,679,58,0.5,0.0,0.5,30.3,30.8,0.0
sig47_to_sig48,47,48,11250.1,11497.8,247.8,21.9,NaN,697,7,0,695,58,0.2,0.0,0.2,29.5,29.7,0.8
sig48_to_sig49,48,49,11497.8,11920.8,422.9,37.0,NaN,697,0,0,692,58,0.0,0.0,0.0,28.6,28.6,0.0
sig49_to_sig50,49,50,11920.8,12135.9,215.1,16.2,NaN,697,0,0,685,58,0.0,0.0,0.0,12.7,12.7,0.0
sig51_to_sig52,51,52,12208.7,12409.7,200.9,18.3,NaN,696,1,0,661,58,0.4,0.0,0.4,13.4,13.7,5.3
sig52_to_sig53,52,53,12409.7,12564.1,154.5,19.6,NaN,696,1,0,633,58,0.0,0.0,0.0,11.9,11.9,0.0

## Per trip-segment detail

Every daytime (trip, segment) with observed travel time, free-flow time, dwell, and the uniform / overflow / signal / congestion / total delay components.

In [9]:
result.daytime_delays.round(1)

,service_date,TRIP_KEY,period,segment_id,observed_travel_time_s,dwell_s,uniform_stop_duration_s,overflow_stop_duration_s,has_signal_stop,free_flow_travel_time_s,red_phase_cap_s,uniform_delay_s,overflow_delay_s,signal_delay_s,congestion_delay_s,total_delay_s
0,2026-01-31,1016.0,day,sig1_to_sig2,37.7,0.0,0.0,0.0,False,23.8,NaN,0.0,0.0,0.0,13.9,13.9
1,2026-01-31,1016.0,day,sig2_to_sig3,11.2,0.0,0.0,0.0,False,7.8,16.0,0.0,0.0,0.0,3.3,3.3
2,2026-01-31,1016.0,day,sig3_to_sig4,37.3,0.0,0.0,0.0,False,32.5,NaN,0.0,0.0,0.0,4.8,4.8
3,2026-01-31,1016.0,day,sig4_to_sig5,3.0,0.0,0.0,0.0,False,3.0,NaN,0.0,0.0,0.0,0.0,0.0
4,2026-01-31,1016.0,day,sig5_to_sig6,12.4,0.0,0.0,0.0,False,12.7,NaN,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32761,2026-02-16,986.0,day,sig47_to_sig48,39.9,0.0,0.0,0.0,False,21.9,NaN,0.0,0.0,0.0,18.0,18.0
32762,2026-02-16,986.0,day,sig48_to_sig49,54.5,0.0,0.0,0.0,False,37.0,NaN,0.0,0.0,0.0,17.5,17.5
32763,2026-02-16,986.0,day,sig49_to_sig50,22.9,0.0,0.0,0.0,False,16.2,NaN,0.0,0.0,0.0,6.7,6.7
32764,2026-02-16,986.0,day,sig51_to_sig52,21.7,0.0,0.0,0.0,False,18.3,NaN,0.0,0.0,0.0,3.5,3.5
32765,2026-02-16,986.0,day,sig52_to_sig53,18.3,0.0,0.0,0.0,False,19.6,NaN,0.0,0.0,0.0,0.0,0.0

## Map of segments

Each analyzed segment is drawn along the shape in a distinct color so adjacent segments are easy to tell apart. Click a segment to see all of its summary values (free-flow time, red-phase cap, trip counts, mean delay components).

In [10]:
import folium
import matplotlib.colors as mcolors
import matplotlib.pyplot as plt

from segment_delay import segment_geometries

segment_geometry = segment_geometries(shapes, SHAPE_ID, result.segments)[["geometry"]]
segment_map = gpd.GeoDataFrame(
    result.segment_summary.round(1).join(segment_geometry),
    geometry="geometry",
    crs=shapes.crs,
).reset_index().to_crs("EPSG:4326")

# Give each segment a distinct color (cycled in route order) so neighbors differ.
palette = [mcolors.to_hex(c) for c in plt.get_cmap("tab20").colors]
segment_map["color"] = [palette[i % len(palette)] for i in range(len(segment_map))]

popup_fields = [c for c in segment_map.columns if c not in ("geometry", "color")]

min_lon, min_lat, max_lon, max_lat = segment_map.total_bounds
segment_delay_map = folium.Map(
    location=[(min_lat + max_lat) / 2, (min_lon + max_lon) / 2],
    zoom_start=13,
    tiles="CartoDB positron",
)
folium.GeoJson(
    segment_map,
    style_function=lambda feature: {
        "color": feature["properties"]["color"],
        "weight": 5,
        "opacity": 0.85,
    },
    popup=folium.GeoJsonPopup(fields=popup_fields),
).add_to(segment_delay_map)
segment_delay_map

In [11]:
example_detail = analyze_trip_segment(
    vehicle_positions, shapes, signals, stops, SHAPE_ID,
    "2026-02-13", 1376, "sig40_to_sig41"
)
plot_trip_segment(
    example_detail,
    title=f"{example.example}: {example.segment_id} — {example.service_date} trip {example.TRIP_KEY}",
)
plt.show()

NameError: name 'analyze_trip_segment' is not defined